name: CI
on: push
jobs:
  tests:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Netbox & Launch (docker)
      run: |
        git clone -b release https://github.com/netbox-community/netbox-docker.git
        cd netbox-docker
        tee docker-compose.override.yml <<EOF
        version: '3.4'
        services:
          netbox:
            ports:
              - 8000:8080
        EOF
        docker-compose pull
        docker-compose up -d
        docker-compose ps
    - name: Launch Pester
      run: |
        ls
        cd ..\Tests\
        tee credential.ps1 <<EOF
        $script:hostname = "127.0.0.1"
        $script:token = "0123456789abcdef0123456789abcdef01234567"
        EOF
        cd integration
        Invoke-Pester *

