name: CI
on: push
jobs:
  tests:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Netbox & Launch (docker)
      run: |
        git clone -b release https://github.com/netbox-community/netbox-docker.git
        cd netbox-docker
        tee docker-compose.override.yml <<EOF
        version: '3.4'
        services:
          netbox:
            ports:
              - 8000:8080
        EOF
        docker-compose pull
        docker-compose up -d
        sleep 120
        docker-compose ps
    - name: Launch Pester
      shell: pwsh
      run: |
        Import-Module ./NetboxPS/NetboxPS.psd1
        cd Tests
        cp credential.docker.ps1 credential.ps1
        cd integration
        Invoke-Pester *

